services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: ACCESS_PASSWORD
        sync: false
      - key: USE_WEBHOOK
        value: True
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com
      - key: PORT
        value: 8443
